### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by takt-op** [takt-op/finance#4]
### Diagramas

- [X] Diagrama de contexto;
- [X] Diagrama de container;
- [X] Diagrama dos componentes (definidos no diagrama de container);
- [x] Diagrama inicial do banco de dados;
- [x] Fluxograma;

### Definições

- [X] Definição da linguagem;
- [X] Definição de frameworks;
    - [X] Framework da linguagem (Laravel);
    - [X] Estilo (Bootstrap);
    - [X] Banco de dados (PostgreSQL);
    - [X] Front-end framework JS (VueJS);

**Comment by panacaqui** [comment]
![Image](https://user-images.githubusercontent.com/39572744/208917066-85e47684-66fc-4774-ab8a-46f76c491544.jpeg)
![Image](https://user-images.githubusercontent.com/39572744/208917065-c8e2cc6c-9c0d-4ae9-a870-f7e0d671a553.jpeg)

**Comment by takt-op** [comment]
Os diagramas estão disponíveis na wiki.
